import type { Metadata } from "next";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';

import { ThemeProvider } from "@mui/material/styles";
import theme from '../styles/theme';
import { CssBaseline } from "@mui/material";
import ModeSwitch from "../components/ModeSwitch";



export const metadata: Metadata = {
  title: "Huerta's Albuquerque Jerky",
  description: "Generated by create next app",
};

export default function RootLayout(props: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider theme={theme}>
          <AppRouterCacheProvider options={{ enableCssLayer: true }}>
            <CssBaseline />
            <ModeSwitch />
            {props.children}
          </AppRouterCacheProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
